//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acme.Dressing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acme.Dressing.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boots.
        /// </summary>
        internal static string BootsLiteral {
            get {
                return ResourceManager.GetString("BootsLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fail.
        /// </summary>
        internal static string FailLiteral {
            get {
                return ResourceManager.GetString("FailLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hat.
        /// </summary>
        internal static string HatLiteral {
            get {
                return ResourceManager.GetString("HatLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jacket.
        /// </summary>
        internal static string JacketLiteral {
            get {
                return ResourceManager.GetString("JacketLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leaving house.
        /// </summary>
        internal static string LeavingHouseLiteral {
            get {
                return ResourceManager.GetString("LeavingHouseLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pants.
        /// </summary>
        internal static string PantsLiteral {
            get {
                return ResourceManager.GetString("PantsLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing PJs.
        /// </summary>
        internal static string RemovingPajamasLiteral {
            get {
                return ResourceManager.GetString("RemovingPajamasLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sandals.
        /// </summary>
        internal static string SandalsLiteral {
            get {
                return ResourceManager.GetString("SandalsLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shirt.
        /// </summary>
        internal static string ShirtLiteral {
            get {
                return ResourceManager.GetString("ShirtLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shorts.
        /// </summary>
        internal static string ShortsLiteral {
            get {
                return ResourceManager.GetString("ShortsLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to socks.
        /// </summary>
        internal static string SocksLiteral {
            get {
                return ResourceManager.GetString("SocksLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sunglasses.
        /// </summary>
        internal static string SunglassesLiteral {
            get {
                return ResourceManager.GetString("SunglassesLiteral", resourceCulture);
            }
        }
    }
}
