//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acme.Dressing.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acme.Dressing.Web.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 1 piece of each type of clothing may be put on.
        /// </summary>
        internal static string Only1PieceOfEachTypeOfClothingMayBePutOn {
            get {
                return ResourceManager.GetString("Only1PieceOfEachTypeOfClothingMayBePutOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pajamas must be taken off before anything else can be put on.
        /// </summary>
        internal static string PajamasMustBeTakenOffBeforeAnythingElseCanBePutOn {
            get {
                return ResourceManager.GetString("PajamasMustBeTakenOffBeforeAnythingElseCanBePutOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pants must be put on before footwear.
        /// </summary>
        internal static string PantsMustBePutOnBeforeFootwear {
            get {
                return ResourceManager.GetString("PantsMustBePutOnBeforeFootwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirt must be put on before headwear.
        /// </summary>
        internal static string ShirtMustBePutOnBeforeHeadwear {
            get {
                return ResourceManager.GetString("ShirtMustBePutOnBeforeHeadwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirt must be put on before jacket.
        /// </summary>
        internal static string ShirtMustBePutOnBeforeJacket {
            get {
                return ResourceManager.GetString("ShirtMustBePutOnBeforeJacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socks must be put on before footwear.
        /// </summary>
        internal static string SocksMustBePutOnBeforeFootwear {
            get {
                return ResourceManager.GetString("SocksMustBePutOnBeforeFootwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot leave the house until all items of clothing are on.
        /// </summary>
        internal static string YouCannotLeaveTheHouseUntilAllItemsOfClothingAreOn {
            get {
                return ResourceManager.GetString("YouCannotLeaveTheHouseUntilAllItemsOfClothingAreOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot put on a jacket when it&apos;s hot.
        /// </summary>
        internal static string YouCannotPutOnJacketWhenItIsHot {
            get {
                return ResourceManager.GetString("YouCannotPutOnJacketWhenItIsHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot put on socks when it&apos;s hot.
        /// </summary>
        internal static string YouCannotPutOnSocksWhenItIsHot {
            get {
                return ResourceManager.GetString("YouCannotPutOnSocksWhenItIsHot", resourceCulture);
            }
        }
    }
}
